gdx/chat/core/src/com/mygdx/game/GdxJDSpiderApp.java

for the issue 67

---

issues/201/15.html
issues/201/cards.html
issues/201/v.html
node/old/js49/plx/p1.js
node/ws/index.js
node/ws/server4_i201.js

a simple game: to find a card.

a simple game: to find a card.  (issue#201)

---

Spring/script/plugin.js
Spring/script/pluginCall.html
Spring/script/video10.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/java/com/pbz/demo/hello/util/engine/JSGraphEngine.java

Please review my design for plugin

for issue 255,plugin design

---

Spring/src/main/java/com/pbz/demo/hello/controller/ImageController.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/resources/templates/video.html
node1/app.js
node1/test/appTest.js

create gif for video

---

index.html
issues/264/script.js
issues/4/c1.js
issues/4/c1Test.html
js/blclass.js
node1/app.js
node1/test/appTest.js

i297: blclass.js

---

index.html
js/plx/p1.js
js/plx/voa/asItIs.js
node1/app4i264.js
node1/test/app4i264Test.js
node1/test/appTest.js

I264 (PR自行化测试升级）

---

issues/323/spring-server-generated/pom.xml
issues/323/spring-server-generated/src/main/java/io/swagger/api/UserApi.java
issues/323/spring-server-generated/src/main/java/io/swagger/api/UserApiController.java

代码分支： i323
解决问题: #323 maven编译报错
测试步骤：
1. 获取分支代码
2. cd Games/issues/323/spring-server-generated
3. mvn clean install
4. java -jar target/swagger-spring-1.0.0.jar
5. 在浏览器中运行， http://localhost:8080

fix compile issues

---

issues/4/c7.js
issues/4/c7/set.js
issues/4/c7Test.html
node1/app/xd.js
node1/test/app4i301Test.js
node1/test/app4i304Test.js
node1/test/app4i330Test.js
node1/test/appTest.js
node1/test/xdTest.js

Xd_i328: 漂泊者象棋 c7Test

---

Spring/script/myplx1.js

I264(plx test)

---

Spring/script/firework.js
node1/app/xd.js
node1/test/xdTest.js

http://localhost:8080/blfw.html
http://localhost:8080/image/video?script=firework.json
close #264

i264: firework refactor

---

node1/app/i343.js
node1/test/i343.js
python/test_serverofnews.py

add new tests

---

Spring/pom.xml
Spring/script/myplx1.js
Spring/script/video12.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/java/com/pbz/demo/hello/util/engine/JSGraphEngine.java
node1/app/python.js
node1/test/python.js
pbzTools/scriptengine/src/main/java/com/pbz/scriptengine/App.java
pbzTools/scriptengine/src/main/java/com/pbz/scriptengine/JSGraphEngine.java
python/sample/test_fanyi.py
python/sample/wxPythonUI.py

代码分支名称：python
所做修改：
1. 修复了几个和canvas插件有关的bug， #341，#350，#346 测试方法见各自的issue
2. #354 在Game/python/sample 目录下放最近学习python的例子作为技术积累，直接运行 python xxx.py可以测试

fix canvas bugs and add sample folder for python

---

Spring/pom.xml
Spring/script/video12.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
node1/app/python.js

code branch: python
fixed issue: #360

fix use mutiple javascript plugins in video json

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/HelloApplication.java
Spring/src/main/java/com/pbz/demo/hello/controller/ImageController.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/java/com/pbz/demo/hello/util/engine/JSGraphEngine.java
Spring/src/test/java/com/pbz/demo/hello/Unit/VideoTest.java
pbzTools/scriptengine/src/main/java/com/pbz/scriptengine/JSGraphEngine.java

code branch: python
fix issues: #364 and #362

json2video endpoint update

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/ImageController.java

for #375, remove the login check!

recover the issue118

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

1. Fixed #369 
2. improved code for #368 
以下是测试用例：
1. java -Dfile.encoding=utf-8 -jar pbz-demo-1.0.9-SNAPSHOT.jar
2. 浏览器输入
http://localhost:8080/image/json2video?script=https://raw.githubusercontent.com/littleflute/cchess/master/blCChess.json&&video=blCChess.mp4

fix download url contains Chinese character

---

node1/app/wx.js
python/swagger/app.py

swagger code-rebuild #412

---

Spring/pom.xml
Spring/script/video13.json
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
node1/test/python.js

I290-working for insert video task

---

python/sample/data.json
python/sample/test_readfile.py

Games\python\sample目录下运行：
python test_readfile.py

add a python sample for reading json file

---

js/blclass.js
node1/app/littlefluteFork.js

_superObjects to voa2video

---

issues/21/c2/c2.js
issues/21/c2/index.html
issues/4/c3/blrTest1.js
issues/4/c3/sample3.js
issues/4/c3/sample4.js
issues/455/dl.bat

c2.js
issues/21/c2/index.html
to do: snap shot current code in sand box.
close #465

 to do: snap shot current code in sand box.

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/FileController.java

close #467
修复JSON文件保存时，加号变成空格的问题

bug fix for issue 467,保存JSON文件时加号变空格

---

issues/4/c6.js
node1/test/python.js

for issue 442, show video from comments

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/CommonController.java
Spring/src/main/java/com/pbz/demo/hello/util/NetAccessUtil.java
node1/test/python.js

I480 add endpoints for comments

---

issues/4/c4.js
issues/4/c5.js

fix bug 494

---

python/swagger/routes/request_api.py

Pre-setting the Environment Variables and add judgement of existed database.

Pre-setting the Environment Variables and add judgement of existed database.

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/CommonController.java
Spring/src/main/java/com/pbz/demo/hello/controller/FileController.java
Spring/src/main/java/com/pbz/demo/hello/model/VideoDoc.java
Spring/src/main/java/com/pbz/demo/hello/service/VideoDocService.java
Spring/src/main/java/com/pbz/demo/hello/service/VideoDocServiceImpl.java
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/resources/templates/videodocs.html
node1/test/python.js

I525-设计实现用comments保存剧本文件

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/service/ScheduledService.java
Spring/src/main/resources/application.properties

I548 bug fix

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/ImageController.java
Spring/src/main/java/com/pbz/demo/hello/service/SubtitleImageService.java
Spring/src/main/java/com/pbz/demo/hello/service/VOAService.java
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/test/java/com/pbz/demo/hello/Unit/VideoTest.java
python/sample/create_worddoc.py

I568-support for LRC file

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

upgrade endpoint save2word to support mutilpy line

---

Spring/pom.xml
Spring/script/video16.json
Spring/src/main/java/com/pbz/demo/hello/service/SubtitleImageService.java
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
node1/test/python.js

I291 SRT and LRC supper object

---

python/i140/face_with_glasses.py

glassed images update python

---

Spring/pom.xml
Spring/script/video16.json
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

I583-字幕文本可以被替换

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/ImageController.java
Spring/src/main/java/com/pbz/demo/hello/util/ImageUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
Spring/src/main/resources/templates/video.html
python/i140/faceDetect.py

I595-subtitle repeat reading & I594-color setting

---

Spring/src/main/java/com/pbz/demo/hello/util/NetAccessUtil.java
issues/4/c4.js
issues/4/c5.js
issues/4/server.js

I600-update the token of Jeremy

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

I605- fix graphic bug

---

Spring/script/video16.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

http://localhost:8080/image/json2video?script=video16.json

I642 - fixed rate issue for lrc supper object

---

issues/4/c3.js
issues/655/index.js
node1/test/xdTest.js

w1: default case 4 userPlxApp

---

issues/630/bin/run.bat

1. go to the Games/issues/630/bin folder
2. run.bat
expect result: will generate a picture which is a signature for littleflute.
Note: the Chrome Browser version should be match with the chromedriver.exe

I630-selenium to hack the web

---

python/i671/58Tongcheng.py

#671 this feature is done by Xiyu. I just check in her code and have a test!

crawer for 58 house data

---

js/blclass.js

update blrHeigh #557

---

js/blclass.js

OK to merge blrHeight

---

issues/689/pom.xml

java -cp .\lib\*;JavaStudy-0.0.2-SNAPSHOT.jar jdbcConn
java -cp .\lib\*;JavaStudy-0.0.2-SNAPSHOT.jar CreatingEmptyPdf

fix for issue 689

---

Spring/pom.xml
Spring/script/duck.svg
Spring/script/video17.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
issues/689/resource/s2.svg
issues/689/resource/s3.svg
issues/689/resource/s4.svg
issues/689/src/svg2png.java
node1/test/python.js

#719
https://user-images.githubusercontent.com/17973348/163532594-ed15bcca-a0d8-4690-acf8-6285e7ff96d5.mp4

add svg plugin in springboot server

---

issues/4/server.js

server.js add a new API for creating issue

add api for creating issue

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/service/DataStreamStoreService.java
Spring/src/main/java/com/pbz/demo/hello/service/ScheduledService.java
issues/4/c8.js

github默认只能读到30条评论数据，以下设置可以改变这个参数
https://api.github.com/repos/jeremyjia/Games/issues/743/comments?per_page=100
https://docs.github.com/en/rest/issues/comments#list-issue-comments

btn-8 bug fix

---

issues/4/c3/sample2.js
js/blclass.js
node1/app/image/index.js
node1/app/word/blMakeP.js
node1/app/word/index.js
node1/app/word/index0.js
node1/expressServer.js
node1/index.js
node1/package-lock.json
node1/package.json
node1/public/d.bat
node1/test/xdTest.js

http://localhost:3001/downloadImage?url=https://littleflute.github.io/blog/img/club.gif&fn=C:\FFOutput\club.gif
http://localhost:3001/downloadImage?url=https://gdb.voanews.com/03190000-0aff-0242-04ad-08da343713da_cx0_cy23_cw0_w1080_h608.jpg&fn=C:\FFOutput\voa1.jpg (China?)
http://localhost:3001/downloadImage?url=http://localhost:8080/voa1.jpg&fn=C:\FFOutput\voa1.jpg

word: voa title, image

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/service/ScheduledService.java
issues/4/c8.js

i750-btn-8 upgrade doc URL

---

index.html
issues/208/express/hello-express/app.js
issues/208/express/hello-express/bin/www
issues/208/express/hello-express/package-lock.json
issues/208/express/hello-express/package.json
issues/208/express/hello-express/public/stylesheets/style.css
issues/208/express/hello-express/routes/index.js
issues/208/express/hello-express/routes/users.js
issues/208/express/hello-express/views/error.jade
issues/208/express/hello-express/views/index.jade
issues/208/express/hello-express/views/layout.jade
issues/21/c6/c6.js
issues/21/c6/index.html
issues/21/index.html
issues/4/c8.html
issues/4/c8.js
js/blclass.js
node1/app/word/index0.js
node1/public/zhipu/ref/2.html
node1/public/zhipu/ref/3.html

Zhipu: 减时线延长问题

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/CommonController.java
Spring/src/main/java/com/pbz/demo/hello/service/DataStreamStoreService.java
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

i767-add API to store data pre issue

---

Spring/Dockerfile
Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/HelloApplication.java
node1/test/python.js

I773-Make docker image for SpringBoot project

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/ExitApp.java
Spring/src/main/java/com/pbz/demo/hello/HelloApplication.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java
issues/4/c8.js

I827 - 分布式服务登记功能

---

node1/test/python.js
pbzTools/scriptengine/plugin/pluginCall.html
pbzTools/scriptengine/plugin/plxBubble.js

plugin management of HTML demo

---

issues/21/canvas.html
issues/21/i876.html
issues/21/index.html
issues/21/testC4Canvas.html
js/blclass.js
node1/test/xdTest.js

canvas video capture

---

pbzTools/scriptengine/plugin/pluginCall.html

plugin to v1.0.5

---

pbzTools/scriptengine/plugin/pluginCall.html
pbzTools/scriptengine/plugin/plxChessBoard.js

Chess audio play with HTML5

---

Spring/pom.xml
Spring/script/plxTextEffects.js
Spring/script/video22.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

Interface design for JS plugin args

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

Use Comment-Plugin in JsonScript

---

Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

add any trace running for super object for java

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

Add trace print for superObject for Java

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/CommonController.java
Spring/src/main/java/com/pbz/demo/hello/model/VideoDoc.java
Spring/src/main/java/com/pbz/demo/hello/service/VideoDocServiceImpl.java
Spring/src/main/resources/templates/videodocs.html

add modify script function for page /videodocs/findAll

---

Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

add hyperlink both video and word

---

Spring/pom.xml
Spring/script/video24.json
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

phthon plugin commentID for audio2wave

---

python/i995/app.py
python/i995/templates/index.html

word cloud sample

---

python/i995/templates/index.html

update fps for 995 image get

---

Spring/pom.xml
Spring/script/overlayVideo.py
Spring/script/video25.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

overlay video interation

---

Spring/script/video26.json
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

add sprite object

---

Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

sprite bug fix

---

js/blclass.js
js/test.js

const btns4MNotes =[
{
"id"	: "1/2/",
"name"	: "1/2/", 
"bgc":"lightgreen"
},
{
"id"	: "1//2//3//4//",
"name"	: "1//2//3//4//", 
"bgc":"lightgreen"
},
{
"id"	: "1/2//3//",
"name"	: "1/2//3//", 
"bgc":"lightgreen"
},
{
"id"	: "1//2//3/",
"name"	: "1//2//3/", 
"bgc":"lightgreen"
},
{
"id"	: "1./2//",
"name"	: "1./2//", 
"bgc":"lightgreen"
},
{
"id"	: "1//2./",
"name"	: "1//2./", 
"bgc":"lightgreen"
},
];
const fn4MNotes = function(os){
const tb = blo0.blDiv(_v,_v.id+"tb4NoteType","noteType","gray");
for(i in os){ 
const b = blo0.blBtn(tb,tb.id+os[i].id,os[i].name,os[i].bgc);
b.style.float = "left";
b.onclick = function(_b,_os,_i){
return function(){			 			 
blo0.blGetTa().value = _os[_i].name; 
}
}(b,os,i);
}
}(btns4MNotes);

musicNote: btns4MNotes+

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

add 4 regx pattern for musicNote drawing

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java

download file by curl for retry download

---

js/blclass.js

blclass v1.6.535:  remove first super object

---

js/blclass.js

isWebsiteAccessible

---

Spring/pom.xml
Spring/script/video29.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

frameSubset for m to n

---

js/blclass.js

1. 增加剧本的时间默认值UI编辑，用于没有场景的视频时间值（秒）
2. 需改删除超级对象，从最后一个元素删除，用户体验好一些

add time & remove so from last

---

index.html
issues/1121/1.html
issues/1121/index.html
issues/1121/script.js
issues/1121/styles.css
js/blclass.js
node1/test/xdTest.js

to do: set frame backgroundColor green chanel.

---

js/blclass.js

修复server_status消息闪烁的问题

---

issues/1127/index.html
issues/1127/melodyGenerator.js
issues/1128/chord.html
issues/1128/chordGenerator.js
issues/1128/index.html
issues/1128/your-script.js
js/blclass.js
node1/test/xdTest.js

back door to edit current frame

---

Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

draw superobjects w/o frames

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/model/SubtitleModel.java
Spring/src/main/java/com/pbz/demo/hello/service/SubtitleImageService.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

LRC upgrade to show last and next subtitle

---

issues/1170/tq3.html

add select user and save feature

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/controller/CommonController.java
Spring/src/main/java/com/pbz/demo/hello/service/DeepseekServiceImpl.java
Spring/src/main/java/com/pbz/demo/hello/service/IDeepseekService.java
issues/1186/auto2ds.html
issues/689/pom.xml
issues/689/src/CrossPlatformDeepseekAutoInput.java

auto input to deepseek

---

Spring/pom.xml
Spring/script/refactor.js
Spring/script/video30.json
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

support animateFrame(time,ctx)

---

Spring/script/ai1.py
issues/1195/aichart.html

ai1.py for loop picture

---

issues/1206/mf.html

fix mf bug

---

Spring/pom.xml
Spring/src/main/java/com/pbz/demo/hello/util/FileUtil.java
Spring/src/main/java/com/pbz/demo/hello/util/JsonSriptParser.java

cut off audio file
